# Generated by Django 3.0.6 on 2020-08-19 05:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('catagory', models.CharField(max_length=15)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=250)),
                ('publish_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
