# Generated by Django 3.0.6 on 2020-08-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='groups',
        ),
    ]
